---
- name: Check Python2.6
  command: python26 -V
  ignore_errors: True
  register: check_python_result

- name: install python26
  yum: name=python26 enablerepo=epel state=present

- name: Check to see if pip is already installed.
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  always_run: true
  register: pip_is_installed

- name: wget --no-check-certificate https://bootstrap.pypa.io/ez_setup.py
  get_url:
    url=https://bootstrap.pypa.io/ez_setup.py
    dest={{ python_download_dir }}
    validate_certs=no
  when: pip_is_installed.rc != 0

- name: python26 ez_setup.py --insecure
  shell: python26 {{ python_download_dir }}/ez_setup.py --insecure
  when: pip_is_installed.rc != 0

- name: easy_install-2.6 pip
  command: easy_install-2.6 pip
  when: pip_is_installed.rc != 0

- name: install pip packages
  shell: source /root/.bashrc && pip install {{item}}
  with_items:
  - "{{ pip_pacakage }}"
