---

- name: install yum 
  yum: name={{ item }} state=present
  with_items:
    - "{{ yum_package }}"

# create nginx user
- name: useradd  
  user: name=nginx shell=/sbin/nologin

# nginx
- name: wget nginx.tar.gz
  get_url: url={{ nginx_dl_url }} dest={{ src_dir }}

- name: tar zxvf httpd.tar.gz -C /usr/src/
  command: chdir={{ src_dir }} tar zxvf {{ nginx_name }}.tar.gz -C /usr/src/

- name: ./configure nginx
  shell: cd /usr/src/{{ nginx_name }};{{ item }}
  with_items:
    - ./configure --user=nginx --group=nginx --prefix=/etc/nginx/ --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --with-http_ssl_module --with-http_realip_module --with-ipv6
    - make
    - make install

# regist build script
- name: create /etc/init.d/nginx
  template: src=nginx.init dest=/etc/init.d/nginx mode=0755

# create cache directory
- name: mkdir -p /var/cache/nginx
  file: dest=/var/cache/nginx state=directory

- name: mkdir -p /var/log/nginx
  file: dest=/var/log/nginx state=directory owner=nginx group=nginx

- name: mkdir -p /etc/nginx/conf.d
  file: dest=/etc/nginx/conf.d state=directory

- name: scp nginx.conf /etc/nginx/nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: scp default.conf /etc/nginx/nginx.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
