---

src_dir: '/usr/local/src'

# cmake_major_version: '2.8'
# cmake_minor_version: '12'
# cmake_version: '{{ cmake_major_version }}.{{ cmake_minor_version }}'
# cmake_name: "cmake-{{ cmake_version }}"
# cmake_dl_url: "http://www.cmake.org/files/v{{ cmake_major_version }}/{{ cmake_name }}.tar.gz"

mysql_major_version: '5.5'
mysql_minor_version: '39'
mysql_version: '{{ mysql_major_version }}.{{ mysql_minor_version }}'
mysql_name: "mysql-{{ mysql_version }}"
mysql_dl_url: "http://dev.mysql.com/get/Downloads/MySQL-{{ mysql_major_version }}/{{ mysql_name }}.tar.gz"

mysql_root_password: root

mysql_module:
  - mysql
  - mysql_client_test
  - mysql_config
  - mysql_convert_table_format
  - mysql_find_rows
  - mysql_fix_extensions
  - mysql_plugin
  - mysql_secure_installation
  - mysql_setpermission
  - mysql_tzinfo_to_sql
  - mysql_upgrade
  - mysql_waitpid
  - mysql_zap
  - mysqlaccess
  - mysqladmin
  - mysqlbinlog
  - mysqlbug
  - mysqlcheck
  - mysqld_multi
  - mysqld_safe
  - mysqldump
  - mysqldumpslow
  - mysqlhotcopy
  - mysqlimport
  - mysqlshow
  - mysqlslap
  - mysqltest

yum_package:
  - cmake
  - ncurses-devel

pip_package:
  - MySQL-python