---

- name: wget go.tar.gz
  get_url: url={{ go_dl_url }} dest={{ src_dir }}

- name: tar -zxvf go.tar.gz -C /usr/local/
  command: chdir={{ src_dir }} tar -zxvf {{ go_name }}.tar.gz -C /usr/local/

- name: yum remove packages
  yum: name=go state=absent

# For root user.
- name: scp bashrc.init /root/.bashrc
  template: src=bashrc.init dest=/root/.bashrc

# For login user (ex: vagrant).
- name: create $HOME/go
  file: dest=/home/{{ login_user }}/go state=directory owner={{ login_user }} group={{ login_user }}

- name: create $HOME/go/bin
  file: dest=/home/{{ login_user }}/go/bin state=directory owner={{ login_user }} group={{ login_user }}

- name: scp bashrc.init $HOME/.bashrc
  template: src=bashrc.init dest=/home/{{ login_user }}/.bashrc
